name: presentation
description: presentation layer
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  domain:
    path: ../domain
  di:
    path: ../di

  loader_overlay: ^4.0.1
  flutter_svg: ^2.0.10+1
  webview_flutter: ^4.8.0
  cupertino_icons: ^1.0.6

  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  result_dart: ^1.1.1
  auto_route: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  test: ^1.24.0

  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1
  auto_route_generator: ^8.1.0
