name: di
description: dependency injection
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  get_it: ^7.7.0

  presentation:
    path: ../presentation
  domain:
    path: ../domain
  data:
    path: ../data

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
