name: domain
description: domain layer
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  test: ^1.24.0
  result_dart: ^1.1.1
  json_serializable: ^6.8.0
